chore: pre-push run lint

diff --git a/.git-hooks/pre-push b/.git-hooks/pre-push
--- a/.git-hooks/pre-push
+++ b/.git-hooks/pre-push
@@ -3,6 +3,9 @@
 # Using `--silent` helps for showing any errs in the first line of the response
 # The first line is picked up by the VS Code GIT UI popup when rc is not 0
 
-npm run --silent lint:fix
-
-exit 0
+if npm run --silent lint:silent ; then
+    exit 0
+else
+    echo "❌ Prettier check failed! Please run lint:fix."
+    exit 1
+fi
